version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  car-service:
    environment:
      - POSTGRES_TEST_DB_STRING=postgres://postgres:password@localhost:5432/car_db_test
      - POSTGRES_DEV_DB_STRING=postgres://postgres:password@localhost:5432/car_db
    image: 'samcart/car-service:latest'
    ports:
      - "3000:3000"
  

  # add web-service

volumes:
  database-data: # named volumes can be managed easier using docker-compose

