version: '3'
services:
  db:
    image: "postgres"
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  car-service:
    depends_on:
      - db
    environment:
      - NODE_ENV=staging
      - POSTGRES_TEST_DB_STRING=postgres://postgres:password@db:5432/car_db_test
      - POSTGRES_DEV_DB_STRING=postgres://postgres:password@db:5432/car_db
    image: 'samcart/car-service:latest'
    networks:
      - backend
    ports:
      - "3000:3000"

  # add web-service

networks:
  backend:

volumes:
  database-data: # named volumes can be managed easier using docker-compose

